python test.py --num_samples 2000 --msm co --load_val --num_hints 2 --filepath cocoeval_2_0.pkl
python test.py --num_samples 2000 --msm co --c_step 0.5 --num_hints 2 --filepath cocoeval_2_0.5.pkl
python test.py --num_samples 2000 --msm co --c_step 1 --num_hints 2 --filepath cocoeval_2_1.pkl
python test.py --num_samples 2000 --msm co --c_step 2 --num_hints 2 --filepath cocoeval_2_2.pkl
python test.py --num_samples 2000 --msm co --c_step 0 --num_hints 3 --filepath cocoeval_3_0.pkl
python test.py --num_samples 2000 --msm co --c_step 0.5 --num_hints 3 --filepath cocoeval_3_0.5.pkl
python test.py --num_samples 2000 --msm co --c_step 1 --num_hints 3 --filepath cocoeval_3_1.pkl
python test.py --num_samples 2000 --msm co --c_step 2 --num_hints 3 --filepath cocoeval_3_2.pkl
python test.py --num_samples 2000 --msm co --c_step 4 --num_hints 3 --filepath cocoeval_3_4.pkl
python test.py --num_samples 2000 --msm co --c_step 0 --num_hints 4 --filepath cocoeval_4_0.pkl
python test.py --num_samples 2000 --msm co --c_step 0.5 --num_hints 4 --filepath cocoeval_4_0.5.pkl
python test.py --num_samples 2000 --msm co --c_step 1 --num_hints 4 --filepath cocoeval_4_1.pkl
python test.py --num_samples 2000 --msm co --c_step 2 --num_hints 4 --filepath cocoeval_4_2.pkl
python test.py --num_samples 2000 --msm co --c_step 3 --num_hints 4 --filepath cocoeval_4_3.pkl
python test.py --num_samples 2000 --msm co --c_step 4 --num_hints 4 --filepath cocoeval_4_4.pkl
python test.py --num_samples 2000 --msm co --c_step 0 --num_hints 5 --filepath cocoeval_5_0.pkl
python test.py --num_samples 2000 --msm co --c_step 0.5 --num_hints 5 --filepath cocoeval_5_0.5.pkl
python test.py --num_samples 2000 --msm co --c_step 1 --num_hints 5 --filepath cocoeval_5_1.pkl
python test.py --num_samples 2000 --msm co --c_step 2 --num_hints 5 --filepath cocoeval_5_2.pkl
python test.py --num_samples 2000 --msm co --c_step 3 --num_hints 5 --filepath cocoeval_5_3.pkl
python test.py --num_samples 2000 --msm co --c_step 4 --num_hints 5 --filepath cocoeval_5_4.pkl
python test.py --num_samples 2000 --msm co --c_step 6 --num_hints 5 --filepath cocoeval_5_6.pkl
